[package]
name = "kitty-server-ssh"
description = "SSH subsystem for the Kitty Server."
version = "0.0.1-alpha.1"
keywords = ["kitty", "server", "ssh", "subsystem"]
categories = ["command-line-utilities"]
authors.workspace = true
repository.workspace = true
edition.workspace = true
license.workspace = true
readme.workspace = true
publish.workspace = true
rust-version.workspace = true

[package.metadata.deb]
maintainer = "Kitsu/VM <kitsuvm@gmail.com>"
depends = "$auto"
suggests = "kitty-server-daemon (>= 0.1.0)"
maintainer-scripts = "debian/"
assets = [
    ["target/release/kitty-server-ssh", "usr/libexec/", "755"],
    ["debian/kitty-server.conf", "etc/ssh/sshd_config.d/", "644"]
]

[dependencies]
clap = { workspace = true, features = ["derive"] }
kitty-server-runtime = { workspace = true }
tokio = { workspace = true, features = ["rt-multi-thread", "net", "io-std"] }
